hyperparameters={
    'targets': ['image_id', '5_o_Clock_Shadow', 'Arched_Eyebrows', 'Attractive',
       'Bags_Under_Eyes', 'Bald', 'Bangs', 'Big_Lips', 'Big_Nose',
       'Black_Hair', 'Blond_Hair', 'Blurry', 'Brown_Hair', 'Bushy_Eyebrows',
       'Chubby', 'Double_Chin', 'Oval_Face', 'Pale_Skin','Pointy_Nose', 'Receding_Hairline', 'Rosy_Cheeks', 'Sideburns','Smiling', 'Straight_Hair', 'Wavy_Hair', 'Wearing_Earrings',  'Eyeglasses', 'Goatee', 'Gray_Hair','Heavy_Makeup', 'High_Cheekbones', 'Male', 'Mouth_Slightly_Open','Mustache', 'Narrow_Eyes', 'No_Beard', 'Wearing_Hat', 'Wearing_Lipstick', 'Wearing_Necklace', 'Wearing_Necktie', 'Young'],
    'height': 218, 
    'width': 178,
    'channels': 3, 
    'batch_size': 16, 
    'epochs': 9, 
    'num_tasks': 40, 
    'initializer': 'he_uniform', 
    'reg_lambda': 1e-3, 
    'output': [2]*40, 
    'lr': 1e-4 , 
    'is_trained': False, 
    'dropout_prob': 0.3,
    'enable_cs': True, 
    'enable_sluice': True,
    'num_layers': 3
}
